# Generated by Django 4.2.6 on 2023-10-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userinfo_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='following', to='user.userinfo'),
        ),
    ]
